name: josco workflow
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
       - name: Building phase
         run: echo"Building in progress"

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing goes
        run: echo"Testing phase happens"

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment goes
        run: echo"Deployment goes"
