name: josco workflow
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: print a hard statement
        run: |
          echo "this is it, Prime has returned"
          uname
          hostname -i
          hostname
          uptime
          free -mh
          df -Th
          
